apiVersion: v1
kind: ReplicationController
metadata:
  name: myJavaapp-rc
spec:
  replicas: 2
  selector:
    app: myJavaapp
    version: 2.6.1
  template:
    metadata:
      labels:
        app: myJavaapp
        version: 2.6.1
    spec:
      containers:
        - name: myownJavacontainer
          image: maha4iac/myonlinebooking:1
          ports:
            - containerPort: 8080
