apiVersion: v1
kind: ReplicationController
metadata:
  name: myapache-rc
spec:
  replicas: 2
  selector: 
    app: myapache
template:
  metadata: 
    labels: 
      app: myapache
  spec:
    containers: 
      - name: myapache-container
        image: ubuntu/apache2
        ports:
          - containerPort: 8080        
