apiVersion: v1
kind: Service
metadata:
  name: myapache-svc
  labels:
    app: myapache
spec:
   type: NodePort
   ports:
   - port: 80
     nodePort: 30001
     protocol: TCP
   selector:
     app: myapache
